### ISSUE TITLE
Roadmap to release

### ISSUE THREAD

**Issue by jakobnissen** [BioJulia/Kmers.jl#23]
This is just a tracking issues for things to remember before release
- [ ] Fix whitespace issues, i.e. trailing whitespace, tabs as whitespace
- [ ] Review all code to check it's not TwoBitNuc-specific (e.g. pushfirst/last is now)
- [ ] Run JET.jl and AQUA.jl on the package and fix any issues
- [ ] Get code coverage up to an acceptable level
- [ ] Do not use blanket `using MyPackage` to prevent breakage when exporting new symbols
- [ ] Add doctests
- [ ] Review all `TODO`s in the code
- [ ] Remove outcommented code

**Comment by kescobo** [comment]
Not sure if you've used Project / Milestones, but I find them quite useful for tracking stuff like this. Totally up to you of course
